---
- name: Update web, NFS, and DB servers
  hosts: webservers, nfs
  become: yes
  tasks:
    - name: Ensure Wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: Update LB server
  hosts: lb, db
  become: yes
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes
      
    - name: Ensure Wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
