---
# Playbook to install Apache on RHEL

- hosts: all
  become: true
  tasks:
    # Install Apache
    - name: Install Apache (httpd)
      ansible.builtin.yum:
        name: httpd
        state: present

    # Ensure Apache service is started and enabled
    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
