# tasks file for webserver - php-todo

# Install GPG key for EPEL
- name: Install GPG key for EPEL
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

# Install GPG key for Remi
- name: Install GPG key for Remi
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi

# Install Apache
- name: Install Apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

# Install EPEL release
- name: Install EPEL release
  become: true
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

# Install dnf-utils and Remi repository
- name: Install dnf-utils and Remi repository
  become: true
  ansible.builtin.yum:
    name:
      - dnf-utils
      - http://rpms.remirepo.net/enterprise/remi-release-9.rpm
    state: present
