---
- hosts: all
  become: yes
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

    # You can uncomment this line if needed
    # - import_playbook: ../static-assignments/common.yml

    - name: tooling assignment
      import_playbook: ../static-assignments/uat-webservers.yml
      tags:
        - webserver

    - name: Nginx assignment
      import_playbook: ../static-assignments/loadbalancers.yml
      tags:
        - nginx_lb

    - name: DB assignment
      import_playbook: ../static-assignments/db-servers.yml
      tags:
        - db
