---
- hosts: all
  name: Include dynamic variables
  become: yes
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

   # - name: tooling assignment
  #    include_tasks: ../static-assignments/uat-webservers.yml
 #     tags:
#        - webserver

    #- name: Nginx assignment
     # include_tasks: ../static-assignments/loadbalancers.yml
    #  tags:
     #   - nginx_lb

  #  - name: DB assignment
   #   include_tasks: ../static-assignments/db-servers.yml
   #   tags:
   #     - db
    - name: artifactory assignment
      include_tasks: ../static-assignments/artifactory.yml
      tags:
        - artfifactory